### ISSUE TITLE
The configured ArgumentParser should be importable

### ISSUE THREAD

**Issue by denkv** [dice-group/dice-embeddings#116]
The configured `parser` in `main.py` should be importable to other modules. It would help to automatically discover argument specifications in integration scenarios.

**Comment by Demirrr** [comment]
Such configuration is defined as a [class Namespace](https://github.com/dice-group/dice-embeddings/blob/a8c457924767b797c3e6cf2f97c51177c49821cd/dicee/config.py#L16).
Would you confirm whether this class helps to automaticaly discover argument specifications?
