### ISSUE TITLE
Need Help on Keci embedding tool

### ISSUE THREAD

**Issue by BillGates98** [dice-group/dice-embeddings#149]
Hello Dr. Caglar Demir,

My name is Happi Happi Bill Gates and I'm a Phd student in Computer Science at the University of Montpellier in France.

I'm writing to you about your work on embeddings. I want to use it to generate a set of feature vectors for alignable and non-alignable instances or entities.

I've been able to install and run it but I'd like to know if keci can really allow me to generate a feature vector from two instances (with properties) that are alignable or not.

I will  give you an example to understand.

 - source.d 
      entity1 property1 value1
      entity1 property2 value2
      entity1 property3 value3
...

- target.d 
     entity-1 property1 value-1
     entity-1 property2 value-2
     entity-1 property3 value-3
...
- same_as.d
     entity1 aligned_with entity-1

What i want is something like that in terms of embeddings :
- embeddings.d
      E(entity1-entity-1) = [f1,..., f_d]

I hope I've made myself clear

Best regards
Bill

**Comment by BillGates98** [comment]
Caglar answer by mail : 

As mentioned earlier, please open an issue in the repository next time if you want to ask a question or a feature request.

I am afraid your question is ill-defined given that entity1 and entity2 are discrete values, subtraction is not defined. 
Yet, you can E(entity-a) - E(entity-b) where entity-a aligned_with entity-b and entity-a and entity-b do occur in the source and target knowledge graphs, respectively.

**Comment by Demirrr** [comment]
Runing this example code https://github.com/dice-group/dice-embeddings/tree/robust#how-to-train results in creating a folder, where embedding files are stored. 

To tackle the embedding alighment problem, you can very well directly these files.
The problem of your interest does not depend on a specific  knowledge graph embedding model. 

If you face any issue in training a KG model, please feel free to open an issue :)
