### ISSUE TITLE
Using tqdm in the cpu train setup

### ISSUE THREAD

**Issue by Demirrr** [dice-group/dice-embeddings#256]
If `--trainer torchCPUTrainer`, 
https://github.com/dice-group/dice-embeddings/blob/0849d2c46ea4bf06d07db6f3d0d2ad01fc230af5/dicee/scripts/run.py#L56
then TorchTrainer is initialized to train an embedding model.
https://github.com/dice-group/dice-embeddings/blob/0849d2c46ea4bf06d07db6f3d0d2ad01fc230af5/dicee/trainer/torch_trainer.py#L9

Yet, TorchTrainer does not use a progress bar. We should integrate https://github.com/tqdm/tqdm into the TorchTrainer that is being initialized. To this end, we should focus on this particular for loop (guess)
https://github.com/dice-group/dice-embeddings/blob/0849d2c46ea4bf06d07db6f3d0d2ad01fc230af5/dicee/trainer/torch_trainer.py#L75

**Comment by sapkotaruz11** [comment]
We need a description tag for the progress bar : Is "Training progress" a suitable description for the progress bar?

**Comment by Demirrr** [comment]
Please train a model with `PL` trainer, to see the displayed info in the progress bar. Ideally, we should use the same description tag. However, it is not a must

**Comment by sapkotaruz11** [comment]
As per the PL trainer, they do not seem to be using a description tag. The way progress bar will be shown for the two trainers is also different, PL trainer shows a single persistent progress bar whereas TorchCPUTrainer shows the logs for each epoch and batch separately.

**Comment by Demirrr** [comment]
Alrighty. Perhaps for the time being, we can settle for two different TQDM progress bars for different trainers

**Comment by Demirrr** [comment]
No worries. Could you please create a feature branch from dev branch and push the changes? So that I can take a look at it :)

**Comment by sapkotaruz11** [comment]
Can you check at https://github.com/dice-group/dice-embeddings/tree/tqdm-support . For now I have just added the progress bar to the loop running all the batch and epochs.

**Comment by Demirrr** [comment]
Completed with https://github.com/dice-group/dice-embeddings/pull/258
