### ISSUE TITLE
Default 'Experiments' Folder Not Created with `--storage_path` Argument

### ISSUE THREAD

**Issue by sshivam95** [dice-group/dice-embeddings#268]
When using the --storage_path argument in the script, the default folder 'Experiments' is not being created automatically. Even when the argument is not specified (thus relying on the default value), the script does not generate the 'Experiments' directory as expected.

The command I used was:
```
dicee --path_single_kg /scratch/hpc-prf-whale/WHALE-data/domain_specific/domain_dataset/hresume_dataset/aesono.fr.txt --path_to_store_single_run Keci_GPU_aesono.fr --model Keci --num_epochs 100 --p 0 --q 1 --embedding_dim 256 --scoring_technique NegSample --eval_model None --batch_size 100_000 --optim SGD
```

**Comment by Demirrr** [comment]
Since you are already using `--path_to_store_single_run ...`, `Experiments` folder will not be generated.
