### ISSUE TITLE
Some entity's embedding missing

### ISSUE THREAD

**Issue by umairq** [dice-group/dice-embeddings#41]
Some entities return null when I use 
pre_trained_kge.get_entity_embeddings(['https://dbpedia.org/resource/Abraham_Lincoln']).
"Abraham Lincoln" is one of a major entity in DBpedia, and it returns null.
It has a DBpedia and Wikipedia page available.
Can you please fix it?
thanks

**Comment by Demirrr** [comment]
Hello @umairq , 

I assume that the missing entity issue is related to the example provided in https://github.com/dice-group/dice-embeddings#using-pre-trained-conex-on-dbpedia-03-2022
It might be the case that some entity embeddings are missing. In [this document](https://github.com/dice-group/dice-embeddings/tree/develop/documents/DBpedia_experiments), we elucidated each step taking during preprocessing DBpedia 03-2022.

Cheers

**Comment by umairq** [comment]
Thanks @Demirrr 
Yes I read the documentation. 
But I think this entity (i.e., https://dbpedia.org/resource/Abraham_Lincoln' ) does not come under the pre-processing removal criteria. As It is not a literal or any other criteria mentioned in document.

**Comment by Demirrr** [comment]
Sorry for the late response.


 >But I think this entity (i.e., https://dbpedia.org/resource/Abraham_Lincoln' ) does not come under the pre-processing removal criteria. As It is not a literal or any other criteria mentioned in document.
Can you please point out exactly why it is excluded?

Unfortunately I do not have time atm to detect at which step of the [preprocessing](https://github.com/dice-group/dice-embeddings/tree/main/documents/DBpedia_experiments) the mentioned entity is removed. 

> can you please provide the very basic steps to re-train it on a newer version of DBpedia? (As I have many examples of such missing entities)

We have [ContinuousExecute](https://github.com/dice-group/dice-embeddings/blob/c05d026b2ed5d83424c4d5f78a210338b4a20b3e/core/executer.py#L569) class implemented to continue the training process by using a pre-trained model. Yet, given that you need embedding vectors for entities haven't previously seen, this class would not be helpful. I am afraid, you would need to construct a training dataset containing all triples of your interest and [train a model a desired hyper params](https://github.com/dice-group/dice-embeddings/blob/main/main.py).

At the time being, DBpedia 2022-03 is the newest version of DBpedia (see https://www.dbpedia.org/blog/dbpedia-snapshot-2022-03-release/)
