### ISSUE TITLE
Istallation Error

### ISSUE THREAD

**Issue by saleem-muhammad** [dice-group/dice-embeddings#85]
I am getting the following error with installing pandas
saleem@3dfed:~$ conda activate dice
(dice) saleem@3dfed:~$ pip3 install pandas==1.5.1
Collecting pandas==1.5.1
  Using cached pandas-1.5.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Collecting pytz>=2020.1
  Using cached pytz-2022.7-py2.py3-none-any.whl (499 kB)
Collecting numpy>=1.20.3
  Using cached numpy-1.24.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, six, numpy, python-dateutil, pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.5.1 requires packaging>=20.0, which is not installed.
matplotlib 3.5.1 requires pillow>=6.2.0, which is not installed.
matplotlib 3.5.1 requires pyparsing>=2.2.1, which is not installed.
Successfully installed numpy-1.24.1 pandas-1.5.1 python-dateutil-2.8.2 pytz-2022.7 six-1.16.0

**Comment by Demirrr** [comment]
Could you please run the full command and share the result ?

```
conda create -n dice python=3.9.12
conda activate dice
# Choose a backend
pip3 install pandas==1.5.1 
pip3 install modin[ray]==0.16.2
pip3 install polars==0.14.26 
pip3 install pyarrow==8.0.0
pip3 install torch==1.13.0 
pip3 install pytorch-lightning==1.6.4
pip3 install scikit-learn==1.1.1
pip3 install pytest==6.2.5
pip3 install gradio==3.0.17

wget https://hobbitdata.informatik.uni-leipzig.de/KG/KGs.zip
unzip KGs.zip
pytest -p no:warnings -x # it takes circa 15 minutes
```
