### ISSUE TITLE
Are the missing triples found by ConEx ranked? 

### ISSUE THREAD

**Issue by hzahera** [dice-group/dice-embeddings#97]
Hi Demir, 

I have a question regardind the output of `find_missing_triples` function, are the output (i.e. missing triples) ranked according w.r.t the confidence score? Which means the first missing_triple has the highest ranking score? 

```
from dicee import KGE
pre_trained_kge = KGE(path_of_pretrained_model_dir='ConEx')
missing_triples = pre_trained_kge.find_missing_triples(confidence=0.95, entities=[''], relations=[''])

```

**Comment by Demirrr** [comment]
The output is **a set of triples**, hence, there is no ranking between the returned/found missing triples.
Each triple in the returned set is a triple whose predicted likelihood score is greater than the confidence threshold.

Please read the [documentation](https://github.com/dice-group/dice-embeddings/blob/287c7c7d223b98aaf9b9972144b909cd5b256add/dicee/knowledge_graph_embeddings.py#L96) for  details.
